[package]
name = "rustimg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
image = "0.25.2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
